import Header from "@/components/admin/Header/Header";
import Sidebar from "@/components/admin/Sidebar/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminLayout({ children }) {
  return (
    <div>
      <Header />
      <Sidebar />
      <div className="px-2 sm:ml-64 mt-[50px]">
        <div className="container mx-auto pt-5">{children}</div>
      </div>
    </div>
  );
}
